# Configuration for all motion datasets
data_paths:
  - spigym/data/sysid_bag/go2_jump_data.npz
  - spigym/data/sysid_bag/go2_sine_data.npz
  - spigym/data/sysid_bag/go2_stand_data.npz
  - spigym/data/sysid_bag/go2_walk_data.npz

