# @package _global_

# defaults:
#   - reward_base

rewards:
  set_reward: Nikhil Go2 Omni Reward
  set_reward_date: 20250904
  reward_scales:
      tracking_lin_vel: 1.5
      tracking_ang_vel: 1.0
      penalty_lin_vel_z: -0.00
      penalty_ang_vel_xy: -0.001
      penalty_orientation: -0.0
      penalty_torques: -0.00002
      penalty_dof_vel: -0.00002
      penalty_dof_acc: -2.5e-7
      penalty_action_rate: -0.001
      
      penalty_feet_ori: -0.0
      
      feet_air_time: 0.5
      
      collision: -5.0
      
      
      
      limits_dof_pos: -10.0
      jump: 10.0
      penalty_feet_contact_forces: -0.00
      tracking_contacts_shaped_force: 4.0
      tracking_contacts_shaped_vel: 4.0
      penalty_feet_slippage: -0.04
      feet_clearance_cmd_linear: -30.0
      dof_pos: 0.0
      orientation_control: -5.0
      raibert_heuristic: -10.0

  desired_stance_width: 0.3
  desired_stance_length: 0.45
  close_feet_threshold: 0.3
  desired_footswing_height: 0.20
  


  only_positive_rewards: False
  omni_style: True
  sigma_rew_neg: 0.02

  # fix upper body
  fix_upper_body: False
  # gait period
  gait_period: 1.0

  gait_force_sigma: 100.0
  gait_vel_sigma: 10.0
  kappa_gait_probs: 0.07
  base_height_target: 0.35

  reward_tracking_sigma:
    lin_vel: 0.25
    ang_vel: 0.25
    height: 0.25

  reward_limit:
    soft_dof_pos_limit: 0.9
    soft_dof_vel_limit: 0.9
    soft_torque_limit: 0.9
    reward_limits_curriculum:
      soft_dof_pos_curriculum: False
      soft_dof_pos_initial_limit: 1.15
      soft_dof_pos_max_limit: 1.15
      soft_dof_pos_min_limit: 0.95
      soft_dof_pos_curriculum_degree: 0.00000025
      soft_dof_pos_curriculum_level_down_threshold: 40
      soft_dof_pos_curriculum_level_up_threshold: 42

      soft_dof_vel_curriculum: False
      soft_dof_vel_initial_limit: 1.15
      soft_dof_vel_max_limit: 1.25
      soft_dof_vel_min_limit: 0.95
      soft_dof_vel_curriculum_degree: 0.00000025
      soft_dof_vel_curriculum_level_down_threshold: 40
      soft_dof_vel_curriculum_level_up_threshold: 42

      soft_torque_curriculum: False
      soft_torque_initial_limit: 1.15
      soft_torque_max_limit: 1.25
      soft_torque_min_limit: 0.85
      soft_torque_curriculum_degree: 0.00000025
      soft_torque_curriculum_level_down_threshold: 40
      soft_torque_curriculum_level_up_threshold: 42


  feet_height_target: 0.12
  locomotion_max_contact_force: 200.0
  desired_feet_max_height_for_this_air: 0.12
  
  reward_penalty_curriculum: False
  reward_initial_penalty_scale : 1.0
  reward_min_penalty_scale: 0.0
  reward_max_penalty_scale: 1.0
  reward_penalty_level_down_threshold: 400
  reward_penalty_level_up_threshold: 700
  reward_penalty_degree: 0.00001
  num_compute_average_epl: 10000

  reward_penalty_reward_names : [
    "penalty_torques",
    "penalty_orientation",
    "penalty_lin_vel_z",
    "penalty_ang_vel_xy",
    "penalty_dof_acc",
    "penalty_dof_vel",
    "penalty_action_rate",
    "penalty_feet_contact_forces",
    "penalty_non_feet_contact",
    "penalty_stumble",
    "penalty_slippage",
    "penalty_feet_ori",
    "penalty_in_the_air",
    "limits_dof_pos",
    "limits_dof_vel",
    "limits_torque",
    "termination",
    "custom_feet_air_time",
    "feet_no_contact",
    "base_height",
    "feet_max_height_for_this_air",
    "penalty_close_feet_xy",
    "penalty_contacts_shaped_vel",
    "penalty_contacts_shaped_force",
    "feet_clearance_cmd_linear",
    "raibert_heuristic"]
