# @package _global_

# defaults:
#   - reward_base

rewards:
  set_reward: Unitree_RL GYM EXACT REWARD
  set_reward_date: 20241008
  only_positive_rewards: False
  reward_scales:
      tracking_lin_vel: 1.0
      tracking_ang_vel: 0.5
      penalty_lin_vel_z: -2.0
      penalty_ang_vel_xy: -0.05
      penalty_orientation: -1.0
      penalty_torques: -0.00002
      penalty_dof_vel: -0.00002
      penalty_dof_acc: -2.5e-7
      penalty_action_rate: -0.2
      # penalty_feet_contact_forces: -0.01
      # penalty_stumble: -10.0
      penalty_slippage: -0.5
      penalty_feet_ori: -0.0
      limits_dof_pos: -10.0
      # limits_dof_vel: -5.0
      # limits_torque: -0.1
      feet_air_time: 0.0
      feet_no_contact: 0.0
      penalty_non_feet_contact: -0.005
      base_height: -1.0
      penalty_feet_height: -0.
      # termination: -500.0
      # penalty_in_the_air: -100.0
      feet_max_height_for_this_air: -100.0
      upperbody_joint_angle_freeze: -0.0
      penalty_close_feet_xy: -0.0
      penalty_contacts_shaped_vel: -4.0
      penalty_contacts_shaped_force: -4.0
      raibert_heuristic: -10.0
      feet_clearance_cmd_linear: -10.0

  desired_stance_width: 0.25
  desired_stance_length: 0.45
  close_feet_threshold: 0.3
  desired_footswing_height: 0.20
  frequencies: 2.0
  phases: 0.0 # Diagonal
  offsets: 0.0 # F / R 0.5 bounding 0.0 pronking
  bounds: 0.0 # L / R
  durations: 0.5 # stand / swing

  gait_force_sigma: 100.0
  gait_vel_sigma: 10.0

  reward_tracking_sigma:
    lin_vel: 0.25
    ang_vel: 0.25
    height: 0.25
  reward_limit:
    soft_dof_pos_limit: 0.9
    soft_dof_vel_limit: 0.9
    soft_torque_limit: 0.9

  feet_height_target: 0.12
  locomotion_max_contact_force: 200.0
  desired_feet_max_height_for_this_air: 0.12
  desired_base_height: 0.45

  reward_penalty_curriculum: False
  reward_initial_penalty_scale : 1.0
  reward_min_penalty_scale: 0.0
  reward_max_penalty_scale: 1.0
  reward_penalty_level_down_threshold: 400
  reward_penalty_level_up_threshold: 700
  reward_penalty_degree: 0.00001
  num_compute_average_epl: 10000

  reward_penalty_reward_names : [
    "penalty_torques",
    "penalty_orientation",
    "penalty_lin_vel_z",
    "penalty_ang_vel_xy",
    "penalty_dof_acc",
    "penalty_dof_vel",
    "penalty_action_rate",
    "penalty_feet_contact_forces",
    "penalty_non_feet_contact",
    "penalty_stumble",
    "penalty_slippage",
    "penalty_feet_ori",
    "penalty_in_the_air",
    "limits_dof_pos",
    "limits_dof_vel",
    "limits_torque",
    "termination",
    "custom_feet_air_time",
    "feet_no_contact",
    "base_height",
    "feet_max_height_for_this_air",
    "penalty_close_feet_xy",
    "penalty_contacts_shaped_vel",
    "penalty_contacts_shaped_force",
    "feet_clearance_cmd_linear",
    "raibert_heuristic"]

