# @package _global_

# defaults:
#   - reward_base

rewards:
  set_reward: Unitree_RL GYM EXACT REWARD
  set_reward_date: 20241008
  only_positive_rewards: False
  reward_scales:
      orientation_control: 3.0
      base_height: 1.0
      collision: -0.1
      feet_distance: -0.5
      penalty_lin_vel_z: -0.5
      penalty_torques: -0.0002
      # penalty_dof_vel: -0.0001
      penalty_dof_acc: -2.5e-7
      penalty_action_rate: -0.1
      penalty_slippage: -0.1
      limits_dof_pos: -10.0
      



  reward_tracking_sigma:
    height: 0.25
  reward_limit:
    soft_dof_pos_limit: 0.9
    soft_dof_vel_limit: 0.9
    soft_torque_limit: 0.9

  feet_height_target: 0.12
  locomotion_max_contact_force: 200.0
  desired_feet_max_height_for_this_air: 0.12
  desired_base_height: 0.34

  reward_penalty_curriculum: False
  reward_initial_penalty_scale : 1.0
  reward_min_penalty_scale: 0.0
  reward_max_penalty_scale: 1.0
  reward_penalty_level_down_threshold: 400
  reward_penalty_level_up_threshold: 700
  reward_penalty_degree: 0.00001
  num_compute_average_epl: 10000

  reward_penalty_reward_names : [
    "penalty_torques",
    "penalty_dof_acc",
    "penalty_dof_vel",
    "penalty_action_rate",
    "penalty_feet_contact_forces",
    "penalty_stumble",
    "penalty_slippage",
    "penalty_feet_ori",
    "penalty_in_the_air",
    "limits_dof_pos",
    "limits_dof_vel",
    "limits_torque",
    "termination",
    "feet_air_time",
    "feet_max_height_for_this_air"]

