# @package _global_

# defaults:
#   - reward_base

rewards:
  set_reward: Unitree_RL GYM EXACT REWARD
  set_reward_date: 20241008
  only_positive_rewards: False
  reward_scales:
      
      ang_vel_z: -1.0
      lin_vel_z: 20.0
      
      feet_height_before_backflip: -30.0
      height_control: 5.0
      actions_symmetry: -0.5
      
      collision: -300.0
      penalty_feet_slippage: -1.0
      penalty_action_rate: -0.01
      ##roll related
      roll_orientation_control: -1.0
      ang_vel_x: 5.0
      gravity_x: -10.0
      feet_distance_x: -1.0
      reach_y_target: 3.0
      reach_x_target: 2.0
      lin_vel_y: -2.0



      ##pitch related
      ang_vel_y: 0.0
      orientation_control: -0.0
      gravity_y: -0.0
      feet_distance: -2.0

      ##regularization:
      penalty_torques: -0.0001
      penalty_dof_acc: -1.1e-5
      penalty_dof_vel: -0.004
      
      


  reward_tracking_sigma:
    lin_vel: 0.25
    ang_vel: 0.25
    height: 0.25
  reward_limit:
    soft_dof_pos_limit: 0.9
    soft_dof_vel_limit: 0.9
    soft_torque_limit: 0.9

  feet_height_target: 0.08
  locomotion_max_contact_force: 200.0
  desired_feet_max_height_for_this_air: 0.12
  base_height_target: 0.48
  base_height: 0.34
  phase_length: 100
  close_feet_threshold: 0.3


  reward_penalty_curriculum: False
  reward_initial_penalty_scale : 1.0
  reward_min_penalty_scale: 0.0
  reward_max_penalty_scale: 1.0
  reward_penalty_level_down_threshold: 400
  reward_penalty_level_up_threshold: 700
  reward_penalty_degree: 0.00001
  num_compute_average_epl: 10000

  reward_penalty_reward_names : [
    "penalty_torques",
    "penalty_dof_acc",
    "penalty_dof_vel",
    "penalty_action_rate",
    "penalty_feet_contact_forces",
    "penalty_stumble",
    "penalty_slippage",
    "penalty_feet_ori",
    "penalty_in_the_air",
    "limits_dof_pos",
    "limits_dof_vel",
    "limits_torque",
    "termination",
    "custom_feet_air_time",
    "feet_no_contact",
    "feet_max_height_for_this_air"]

