# @package _global_

defaults:
  - terrain_base

terrain:
  mesh_type : 'heightfield' # "heightfield" # none, plane, heightfield or trimesh
  horizontal_scale : 0.1 # [m]
  vertical_scale : 0.005 # [m]
  border_size : 40 # [m]
  curriculum : True
  # curriculum : False
  static_friction: 1.0
  dynamic_friction: 1.0
  restitution: 0.0
  # rough terrain only:
  measure_heights : False # keep it False
  measured_points_x : [ 0.] # 1mx1.6m rectangle (without center line)
  measured_points_y : [ 0.]
  selected : False # select a unique terrain type and pass all arguments
  terrain_kwargs : null # Dict of arguments for selected terrain
  max_init_terrain_level : 1 # starting curriculum state
  terrain_length : 3.5
  terrain_width : 3.5
  num_rows: 64 # number of terrain rows (levels)
  num_cols : 64 # number of terrain cols (types)
  terrain_types : ['block']  # do not duplicate!
  terrain_proportions : [1.0]
  block_height : 0.005
  block_width: 0.8
  # trimesh only:
  slope_treshold : 0.75 # slopes above this threshold will be corrected to vertical surfaces