# @package _global_

# defaults:
#   - reward_base

rewards:
  set_reward: Guanqi
  set_reward_date: 20241216
  only_positive_rewards: False
  reward_scales:
      # joint_pos_tracking: 1.0
      # joint_vel_tracking: 1.0
      # ctrl_tracking: 1.0
      # base_pos_tracking: 1.0
      # base_rot_tracking: 1.0
      # base_lin_vel_tracking: 1.0
      # base_ang_vel_tracking: 1.0
      fisher_infomation_matrix: 1.0
      joint_pos_tracking: 3.0
      joint_vel_tracking: 0.009
      # ctrl_tracking: 0.004
      ctrl_tracking: 0.00000001 # test no torque tracking
      base_pos_tracking: 200.0
      base_rot_tracking: 30.0
      base_lin_vel_tracking: 2.0
      base_ang_vel_tracking: 0.1
  regularization_scales:
      # base_mass: 0.0
      # base_xcom: 1.0
      # base_ycom: 1.0
      # base_zcom: 1.0
      # base_xinertia: 0.01
      # base_yinertia: 0.01
      # base_zinertia: 0.01
      base_mass: 0.0001
      base_xcom: 10.0
      base_ycom: 10.0
      base_zcom: 10.0
      base_xinertia: 0.3
      base_yinertia: 0.3
      base_zinertia: 0.3
      
      # motor_model:
      # act2tau_scalar:
      scalar_gain: 0.01
      
      # act2tau_vec3:
      calf_gain: 0.1
      hip_gain: 0.1
      thigh_gain: 0.1

      # act2tau_vec3_tanh:
      calf_a: 0.01
      calf_b: 0.01
      hip_a: 0.01
      hip_b: 0.01
      thigh_a: 0.01
      thigh_b: 0.01


  reward_limit:
    soft_dof_pos_limit: 0.95
    soft_dof_vel_limit: 0.95
    soft_torque_limit: 0.95
  # locomotion_max_contact_force: 200.0
  # desired_feet_max_height_for_this_air: 0.2

  reward_penalty_curriculum: False
  reward_initial_penalty_scale : 0.1
  reward_min_penalty_scale: 0.0
  reward_max_penalty_scale: 1.0
  reward_penalty_level_down_threshold: 50
  reward_penalty_level_up_threshold: 100
  reward_penalty_degree: 0.00001
  num_compute_average_epl: 10000

  reward_penalty_reward_names : [
    "penalty_torques",
    "penalty_dof_acc",
    "penalty_dof_vel",
    "penalty_action_rate",
    "limits_dof_pos",
    "limits_dof_vel",
    "limits_torque"]