# @package _global_
#def_dr
# domain_rand:
#   # push robots
#   push_robots : False
#   push_interval_s : [15, 16]
#   max_push_vel_xy : 0.3

#   # base com
#   randomize_base_com : True
#   base_com_range:
#     x : [-0.1, 0.1]
#     y : [-0.1, 0.1]
#     z : [-0.1, 0.1]

#   # link mass
#   randomize_link_mass : True
#   link_mass_range : [0.8, 1.2]

#   # base inertia
#   randomize_base_inertia : False
#   base_inertia_range:
#     x : [0.0, 0.075]
#     y : [0.0, 0.075]
#     z : [-0.0, 0.5]

#   # pd gain
#   randomize_pd_gain : True
#   kp_range : [0.9, 1.1]
#   kd_range : [0.9, 1.1]

#   #motor model
#   randomize_motor_model : False
#   motor_model_range:
#     hip : [22, 25]
#     thigh : [18, 22]
#     calf : [22, 25]
#   # friction
#   randomize_friction : True
#   friction_range : [0.5, 1.25]

#   # base mass
#   randomize_base_mass : False

#   # rfi
#   randomize_torque_rfi : True
#   rfi_lim : 0.1
#   randomize_rfi_lim : False
#   rfi_lim_range : [0.9, 1.1]


#   # control delay
#   randomize_ctrl_delay : False
#   ctrl_delay_step_range : [0, 2] # integer max real delay is 90ms



#### high_dr #####
# domain_rand:
#   # push robots
#   push_robots : False
#   push_interval_s : [15, 16]
#   max_push_vel_xy : 0.3

#   # base com
#   randomize_base_com : True
#   base_com_range:
#     x : [-0.2, 0.2]
#     y : [-0.2, 0.2]
#     z : [-0.2, 0.2]

#   # link mass
#   randomize_link_mass : True
#   link_mass_range : [0.6, 1.2]

#   # base inertia
#   randomize_base_inertia : True
#   base_inertia_range:
#     x : [0.0, 0.2]
#     y : [0.0, 0.2]
#     z : [-0.0, 0.2]

#   # pd gain
#   randomize_pd_gain : True
#   kp_range : [0.9, 1.1]
#   kd_range : [0.9, 1.1]

#   #motor model
#   randomize_motor_model : False
#   motor_model_range:
#     hip : [22, 25]
#     thigh : [18, 22]
#     calf : [22, 25]
#   # friction
#   randomize_friction : True
#   friction_range : [0.5, 1.25]

#   # base mass
#   randomize_base_mass : False

#   # rfi
#   randomize_torque_rfi : True
#   rfi_lim : 0.1
#   randomize_rfi_lim : False
#   rfi_lim_range : [0.9, 1.1]


#   # control delay
#   randomize_ctrl_delay : False
#   ctrl_delay_step_range : [0, 2] # integer max real delay is 90ms


### sysid_def_dr ####

# domain_rand:
#   # push robots
#   push_robots : False
#   push_interval_s : [15, 16]
#   max_push_vel_xy : 0.3

#   # base com
#   randomize_base_com : True
#   base_com_range:
#     x : [-0.1, 0.1]
#     y : [-0.1, 0.1]
#     z : [-0.1, 0.1]

#   # link mass
#   randomize_link_mass : True
#   link_mass_range : [0.8, 1.2]

#   # base inertia
#   randomize_base_inertia : True
#   base_inertia_range:
#     x : [-0.1, 0.1]
#     y : [-0.1, 0.1]
#     z : [-0.1, 0.1]

#   # pd gain
#   randomize_pd_gain : True
#   kp_range : [0.9, 1.1]
#   kd_range : [0.9, 1.1]

#   #motor model
#   randomize_motor_model : True
#   motor_model_range:
#     hip : [22, 24]
#     thigh : [18, 22]
#     calf : [22, 24]
#   # friction
#   randomize_friction : True
#   friction_range : [0.5, 1.0]

#   # base mass
#   randomize_base_mass : False

#   # rfi
#   randomize_torque_rfi : True
#   rfi_lim : 0.1
#   randomize_rfi_lim : False
#   rfi_lim_range : [0.9, 1.1]


#   # control delay
#   randomize_ctrl_delay : False
#   ctrl_delay_step_range : [0, 2] # integer max real delay is 90ms


### sysid_uq_dr ####
# domain_rand:
#   # push robots
#   push_robots : False
#   push_interval_s : [15, 16]
#   max_push_vel_xy : 0.3

#   # base com
#   randomize_base_com : True
#   base_com_range:
#     x : [-0.1, 0.1]
#     y : [-0.1, 0.1]
#     z : [-0.1, 0.1]
  
#   # base_com_range:
#   #   x : [-0.1, 0.1]
#   #   y : [-0.1, 0.1]
#   #   z : [-0.1, 0.1]

#   # link mass
#   randomize_link_mass : True
#   link_mass_range : [0.8, 1.3]

#   # base inertia
#   randomize_base_inertia : False
#   base_inertia_range:
#     x : [-0.08953979, 0.08953979]
#     y : [-0.09695391, 0.09695391]
#     z : [-0.08554757, 0.08554757]
  
#   # base_inertia_range:
#   #   x : [-0.1, 0.1]
#   #   y : [-0.1, 0.1]
#   #   z : [-0.1,0.1]

#   # randomize_base_inertia : True
#   # base_inertia_range:
#   #   x : [-0.075, 0.075]
#   #   y : [-0.075, 0.075]
#   #   z : [-0.075, 0.075]

#   # pd gain
#   randomize_pd_gain : True
#   kp_range : [0.9, 1.1]
#   kd_range : [0.9, 1.1]

#   #motor model
#   randomize_motor_model : False
#   motor_model_range:
#     hip : [20.314, 25.14]
#     thigh : [17.762, 22.726]
#     calf : [20.397, 25.007]
  
#   # randomize_motor_model : True
#   # # motor_model_range:
#   # #   hip : [22, 25.]
#   # #   thigh : [17.762, 22.026]
#   # #   calf : [22, 25.007]
#   # motor_model_range:
#   #   hip : [22, 25]
#   #   thigh : [18, 22]
#   #   calf : [22, 25]

#   # motor_model_range:
#   #   hip : [22, 24]
#   #   thigh : [18, 22]
#   #   calf : [22, 24]
#   # friction
#   randomize_friction : True
#   # friction_range : [0.5, 1.0]
#   friction_range : [0.5, 1.0]

#   # base mass
#   randomize_base_mass : False

#   # rfi
#   randomize_torque_rfi : True
#   rfi_lim : 0.1
#   randomize_rfi_lim : False
#   rfi_lim_range : [0.9, 1.1]


#   # control delay
#   randomize_ctrl_delay : False
#   ctrl_delay_step_range : [0, 2] # integer max real delay is 90ms


### active_sysid_uq_dr ####
# domain_rand:
#   # push robots
#   push_robots : False
#   push_interval_s : [15, 16]
#   max_push_vel_xy : 0.3

#   # base com
#   randomize_base_com : True
#   # base_com_range:
#   #   x : [-0.0149, 0.0149]
#   #   y : [-0.0157, 0.0157]
#   #   z : [-0.0156, 0.0156]
  
#   base_com_range:
#     x : [-0.1, 0.1]
#     y : [-0.1, 0.1]
#     z : [-0.1, 0.1]

#   # link mass
#   randomize_link_mass : True
#   link_mass_range : [0.9, 1.2]

#   # base inertia
#   randomize_base_inertia : false
#   base_inertia_range:
#     x : [-0.0879, 0.0879]
#     y : [-0.0802, 0.0802]
#     z : [-0.0846, 0.0846]
  
#   # base_inertia_range:
#   #   x : [-0.1, 0.1]
#   #   y : [-0.1, 0.1]
#   #   z : [-0.1,0.1]

#   # randomize_base_inertia : True
#   # base_inertia_range:
#   #   x : [-0.075, 0.075]
#   #   y : [-0.075, 0.075]
#   #   z : [-0.075, 0.075]

#   # pd gain
#   randomize_pd_gain : True
#   kp_range : [0.9, 1.1]
#   kd_range : [0.9, 1.1]

#   #motor model
#   randomize_motor_model : True
#   motor_model_range:
#     hip : [20.014, 25.12]
#     thigh : [22.187, 27.751]
#     calf : [19.682, 25.364]
  
#   # randomize_motor_model : True
#   # # motor_model_range:
#   # #   hip : [22, 25.]
#   # #   thigh : [17.762, 22.026]
#   # #   calf : [22, 25.007]
#   # motor_model_range:
#   #   hip : [22, 25]
#   #   thigh : [18, 22]
#   #   calf : [22, 25]

#   # motor_model_range:
#   #   hip : [22, 24]
#   #   thigh : [18, 22]
#   #   calf : [22, 24]
#   # friction
#   randomize_friction : True
#   # friction_range : [0.5, 1.0]
#   friction_range : [0.5, 1.25]

#   # base mass
#   randomize_base_mass : False

#   # rfi
#   randomize_torque_rfi : True
#   rfi_lim : 0.1
#   randomize_rfi_lim : False
#   rfi_lim_range : [0.9, 1.1]


#   # control delay
#   randomize_ctrl_delay : False
#   ctrl_delay_step_range : [0, 2] # integer max real delay is 90ms


## active_sysid_uq_dr ####
domain_rand:
  # push robots
  push_robots : False
  push_interval_s : [15, 16]
  max_push_vel_xy : 0.3

  # base com
  randomize_base_com : True
  
  
  # base_com_range:
  #   x : [-0.01771147,0.01771147]
  #   y : [-0.01377559,0.01377559]
    # z : [-0.01836745,0.01836745]

  base_com_range:
    x : [-0.1,0.1]
    y : [-0.1,0.1]
    z : [-0.1,0.1]

  # link mass
  randomize_link_mass : True
  link_mass_range : [0.86, 1.14]

  # base inertia
  randomize_base_inertia : false
  base_inertia_range:
    x : [-0.09183724, 0.09183724]
    y : [-0.09052528, 0.09052528]
    z : [-0.09183724, 0.09183724]
  
  # base_inertia_range:
  #   x : [-0.1, 0.1]
  #   y : [-0.1, 0.1]
  #   z : [-0.1,0.1]

  # randomize_base_inertia : True
  # base_inertia_range:
  #   x : [-0.075, 0.075]
  #   y : [-0.075, 0.075]
  #   z : [-0.075, 0.075]

  # pd gain
  randomize_pd_gain : True
  kp_range : [0.9, 1.1]
  kd_range : [0.9, 1.1]

  #motor model
  randomize_motor_model : True
  motor_model_range:
    hip : [23.131, 28.901]
    thigh : [19.983, 25.781]
    calf : [20.091, 25.637]
  
  # randomize_motor_model : True
  # # motor_model_range:
  # #   hip : [22, 25.]
  # #   thigh : [17.762, 22.026]
  # #   calf : [22, 25.007]
  # motor_model_range:
  #   hip : [22, 25]
  #   thigh : [18, 22]
  #   calf : [22, 25]

  # motor_model_range:
  #   hip : [22, 24]
  #   thigh : [18, 22]
  #   calf : [22, 24]
  # friction
  randomize_friction : True
  friction_range : [0.5, 1.25]
  # friction_range : [0.5, 1.25]

  # base mass
  randomize_base_mass : False

  # rfi
  randomize_torque_rfi : True
  rfi_lim : 0.1
  randomize_rfi_lim : False
  rfi_lim_range : [0.9, 1.1]


  # control delay
  randomize_ctrl_delay : False
  ctrl_delay_step_range : [0, 2] # integer max real delay is 90ms





















#h10
# domain_rand:
#   # push robots
#   push_robots : False
#   push_interval_s : [15, 16]
#   max_push_vel_xy : 0.3

#   # base com
#   randomize_base_com : True
#   base_com_range:
#     x : [-0.02100146, 0.02100146]
#     y : [-0.02167892, 0.02167892]
#     z : [-0.01490426, 0.01490426]

#   # link mass
#   randomize_link_mass : True
#   link_mass_range : [0.8, 1.2]

#   # base inertia
#   randomize_base_inertia : True
#   base_inertia_range:
#     x : [-0.10094249,0.10094249]
#     y : [-0.09891009,0.09891009]
#     z : [-0.10229742,0.10229742]

#   # pd gain
#   randomize_pd_gain : True
#   kp_range : [0.9, 1.1]
#   kd_range : [0.9, 1.1]

#   #motor model
#   randomize_motor_model : True
#   motor_model_range:
#     hip : [19.5735259, 23.940]
#     thigh : [17.765, 22.356]
#     calf : [19.07874832, 23.543]
#   # friction
#   randomize_friction : True
#   friction_range : [0.5, 1.0]

#   # base mass
#   randomize_base_mass : False

#   # rfi
#   randomize_torque_rfi : True
#   rfi_lim : 0.1
#   randomize_rfi_lim : False
#   rfi_lim_range : [0.9, 1.1]


#   # control delay
#   randomize_ctrl_delay : False
#   ctrl_delay_step_range : [0, 2] # integer max real delay is 90ms

#h50
# domain_rand:
#   # push robots
#   push_robots : False
#   push_interval_s : [15, 16]
#   max_push_vel_xy : 0.3

#   # base com
#   randomize_base_com : True
#   base_com_range:
#     x : [-0.02135395,0.02135395]
#     y : [-0.02068664,0.02068664]
#     z : [-0.01534815,0.01534815]

#   # link mass
#   randomize_link_mass : True
#   link_mass_range : [0.82, 1.18]

#   # base inertia
#   randomize_base_inertia : True
#   base_inertia_range:
#     x : [-0.10143127, 0.10143127]
#     y : [-0.10076396, 0.10076396]
#     z : [-0.10810438, 0.10810438]

#   # pd gain
#   randomize_pd_gain : True
#   kp_range : [0.9, 1.1]
#   kd_range : [0.9, 1.1]

#   #motor model
#   randomize_motor_model : True
#   motor_model_range:
#     hip : [19.816, 24.302]
#     thigh : [19.842, 24.16]
#     calf : [19.672, 23.994]
#   # friction
#   randomize_friction : True
#   friction_range : [0.5, 1.0]

#   # base mass
#   randomize_base_mass : False

#   # rfi
#   randomize_torque_rfi : True
#   rfi_lim : 0.1
#   randomize_rfi_lim : False
#   rfi_lim_range : [0.9, 1.1]


#   # control delay
#   randomize_ctrl_delay : False
#   ctrl_delay_step_range : [0, 2] # integer max real delay is 90ms


# #h100
# domain_rand:
#   # push robots
#   push_robots : False
#   push_interval_s : [15, 16]
#   max_push_vel_xy : 0.3

#   # base com
#   randomize_base_com : True
#   base_com_range:
#     x : [-0.02137834,0.02137834]
#     y : [-0.02064116,0.02064116]
#     z : [-0.01621805,0.01621805]

#   # link mass
#   randomize_link_mass : True
#   link_mass_range : [0.87, 1.13]

#   # base inertia
#   randomize_base_inertia : True
#   base_inertia_range:
#     x : [-0.11573791,0.11573791]
#     y : [-0.11057762,0.11057762]
#     z : [-0.10541733,0.10541733]

#   # pd gain
#   randomize_pd_gain : True
#   kp_range : [0.9, 1.1]
#   kd_range : [0.9, 1.1]

#   #motor model
#   randomize_motor_model : True
#   motor_model_range:
#     hip : [19.485, 24.385]
#     thigh : [19.774, 24.57]
#     calf : [19.279, 24.231]
#   # friction
#   randomize_friction : True
#   friction_range : [0.5, 1.0]

#   # base mass
#   randomize_base_mass : False

#   # rfi
#   randomize_torque_rfi : True
#   rfi_lim : 0.1
#   randomize_rfi_lim : False
#   rfi_lim_range : [0.9, 1.1]


#   # control delay
#   randomize_ctrl_delay : False
#   ctrl_delay_step_range : [0, 2] # integer max real delay is 90ms


# #h200
# domain_rand:
#   # push robots
#   push_robots : False
#   push_interval_s : [15, 16]
#   max_push_vel_xy : 0.3

#   # base com
#   randomize_base_com : True
#   base_com_range:
#     x : [-0.023, 0.023]
#     y : [-0.017, 0.017]
#     z : [-0.016, 0.016]

#   # link mass
#   randomize_link_mass : True
#   link_mass_range : [0.864, 1.135]

#   # base inertia
#   randomize_base_inertia : True
#   base_inertia_range:
#     x : [-0.104, 0.104]
#     y : [-0.105, 0.105]
#     z : [-0.108, 0.108]

#   # pd gain
#   randomize_pd_gain : True
#   kp_range : [0.9, 1.1]
#   kd_range : [0.9, 1.1]

#   #motor model
#   randomize_motor_model : True
#   motor_model_range:
#     hip : [18.118, 23.238]
#     thigh : [19.083, 23.827]
#     calf : [19.557, 24.241]
#   # friction
#   randomize_friction : True
#   friction_range : [0.5, 1.0]

#   # base mass
#   randomize_base_mass : False

#   # rfi
#   randomize_torque_rfi : True
#   rfi_lim : 0.1
#   randomize_rfi_lim : False
#   rfi_lim_range : [0.9, 1.1]


#   # control delay
#   randomize_ctrl_delay : False
#   ctrl_delay_step_range : [0, 2] # integer max real delay is 90ms


# #h400

# domain_rand:
#   #push robots
#   push_robots : False
#   push_interval_s : [15, 16]
#   max_push_vel_xy : 0.3

#   # base com
#   randomize_base_com : True
#   base_com_range:
#     x : [-0.021, 0.021]
#     y : [-0.016, 0.016]
#     z : [-0.018, 0.018]

#   # link mass
#   randomize_link_mass : True
#   link_mass_range : [0.78, 1.19]

#   # base inertia
#   randomize_base_inertia : True
#   base_inertia_range:
#     x : [-0.106, 0.106]
#     y : [-0.115, 0.115]
#     z : [-0.117, 0.117]

#   # pd gain
#   randomize_pd_gain : True
#   kp_range : [0.9, 1.1]
#   kd_range : [0.9, 1.1]

#   #motor model
#   randomize_motor_model : True
#   motor_model_range:
#     hip : [19.909, 25.335]
#     thigh : [19.552, 24.922]
#     calf : [20.464, 25.636]
#   # friction
#   randomize_friction : True
#   friction_range : [0.5, 1.0]

#   # base mass
#   randomize_base_mass : False

#   # rfi
#   randomize_torque_rfi : True
#   rfi_lim : 0.1
#   randomize_rfi_lim : False
#   rfi_lim_range : [0.9, 1.1]


#   # control delay
#   randomize_ctrl_delay : False
#   ctrl_delay_step_range : [0, 2] # integer max real delay is 90ms


# no_mtr
# domain_rand:
#   # push robots
#   push_robots : False
#   push_interval_s : [15, 16]
#   max_push_vel_xy : 0.3

#   # base com
#   randomize_base_com : True
#   base_com_range:
#     x : [-0.027,0.027]
#     y : [-0.027,0.027]
#     z : [-0.027,0.027]

#   # link mass
#   randomize_link_mass : True
#   link_mass_range : [0.8, 1.2]

#   # base inertia
#   randomize_base_inertia : False
#   base_inertia_range:
#     x : [-0.148, 0.148]
#     y : [-0.161, 0.161]
#     z : [-0.141, 0.141]

#   # pd gain
#   randomize_pd_gain : True
#   kp_range : [0.9, 1.1]
#   kd_range : [0.9, 1.1]

#   #motor model
#   randomize_motor_model : False
#   motor_model_range:
#     hip : [22, 25]
#     thigh : [18, 22]
#     calf : [22, 25]
#   # friction
#   randomize_friction : True
#   friction_range : [0.5, 1.0]

#   # base mass
#   randomize_base_mass : False

#   # rfi
#   randomize_torque_rfi : True
#   rfi_lim : 0.1
#   randomize_rfi_lim : False
#   rfi_lim_range : [0.9, 1.1]


#   # control delay
#   randomize_ctrl_delay : False
#   ctrl_delay_step_range : [0, 2] # integer max real delay is 90ms


# linear_mtr
# domain_rand:
#   # push robots
#   push_robots : False
#   push_interval_s : [15, 16]
#   max_push_vel_xy : 0.3

#   # base com
#   randomize_base_com : True
#   base_com_range:
#     x : [-0.026, 0.026]
#     y : [-0.026, 0.026]
#     z : [-0.026, 0.026]

#   # link mass
#   randomize_link_mass : True
#   link_mass_range : [0.761, 1.24]

#   # base inertia
#   randomize_base_inertia : False
#   base_inertia_range:
#     x : [-0.155,0.155]
#     y : [-0.156, 0.156]
#     z : [-0.130, 0.130]

#   # pd gain
#   randomize_pd_gain : True
#   kp_range : [0.9, 1.1]
#   kd_range : [0.9, 1.1]

#   #motor model
#   randomize_motor_model : True
#   motor_model_range:
#     hip : [0.8451,1.15]
#     thigh : [0.892, 1.175]
#     calf : [0.93,1.03]
#   # friction
#   randomize_friction : True
#   friction_range : [0.5, 1.0]

#   # base mass
#   randomize_base_mass : False

#   # rfi
#   randomize_torque_rfi : True
#   rfi_lim : 0.1
#   randomize_rfi_lim : False
#   rfi_lim_range : [0.9, 1.1]


#   # control delay
#   randomize_ctrl_delay : False
#   ctrl_delay_step_range : [0, 2] # integer max real delay is 90ms


# tanhscalar_mtr
# domain_rand:
#   # push robots
#   push_robots : False
#   push_interval_s : [15, 16]
#   max_push_vel_xy : 0.3

#   # base com
#   randomize_base_com : True
#   base_com_range:
#     x : [-0.1, 0.1]
#     y : [-0.1, 0.1]
#     z : [-0.1, 0.1]

#   # link mass
#   randomize_link_mass : True
#   link_mass_range : [0.766, 1.23]

#   # base inertia
#   randomize_base_inertia : False
#   base_inertia_range:
#     x : [-0.120,0.120]
#     y : [-0.120, 0.120]
#     z : [-0.10, 0.10]

#   # pd gain
#   randomize_pd_gain : True
#   kp_range : [0.9, 1.1]
#   kd_range : [0.9, 1.1]

#   #motor model
#   randomize_motor_model : True
#   motor_model_range: [17.952,25.772]
#   # friction
#   randomize_friction : True
#   friction_range : [0.5, 1.0]

#   # base mass
#   randomize_base_mass : False

#   # rfi
#   randomize_torque_rfi : True
#   rfi_lim : 0.1
#   randomize_rfi_lim : False
#   rfi_lim_range : [0.9, 1.1]


#   # control delay
#   randomize_ctrl_delay : False
#   ctrl_delay_step_range : [0, 2] # integer max real delay is 90ms
