# @package _global_
## def_dr
# domain_rand:
#   # push robots
#   push_robots : False
#   push_interval_s : [15, 16]
#   max_push_vel_xy : 0.3

#   # base com

#   randomize_base_com : True
#   base_com_range:
#     x : [-0.1, 0.1]
#     y : [-0.1, 0.1]
#     z : [-0.1, 0.1]

#   # link mass
#   randomize_link_mass : True
#   link_mass_range : [0.8, 1.2]

#   # base inertia
#   randomize_base_inertia : False
#   base_inertia_range:
#     x : [0.0, 0.075]
#     y : [0.0, 0.075]
#     z : [-0.0, 0.5]

#   # pd gain
#   randomize_pd_gain : True
#   kp_range : [0.9, 1.1]
#   kd_range : [0.9, 1.1]

#   #motor model
#   randomize_motor_model : False
#   motor_model_range:
#     hip : [22, 25]
#     thigh : [18, 22]
#     calf : [22, 25]
#   # friction
#   randomize_friction : True
#   friction_range : [-0.5, 1.25]

#   # base mass
#   randomize_base_mass : False

#   # rfi
#   randomize_torque_rfi : True
#   rfi_lim : 0.1
#   randomize_rfi_lim : False
#   rfi_lim_range : [0.9, 1.1]


#   # control delay
#   randomize_ctrl_delay : False
#   ctrl_delay_step_range : [0, 2] # integer max real delay is 90ms



#### high_dr #####
# domain_rand:
#   # push robots
#   push_robots : False
#   push_interval_s : [15, 16]
#   max_push_vel_xy : 0.3

#   # base com
#   randomize_base_com : True
#   base_com_range:
#     x : [-0.2, 0.2]
#     y : [-0.2, 0.2]
#     z : [-0.2, 0.2]

#   # link mass
#   randomize_link_mass : True
#   link_mass_range : [0.8, 1.8]

#   # base inertia
#   randomize_base_inertia : True
#   base_inertia_range:
#     x : [0.0, 0.075]
#     y : [0.0, 0.075]
#     z : [-0.0, 0.5]

#   # pd gain
#   randomize_pd_gain : True
#   kp_range : [0.9, 1.1]
#   kd_range : [0.9, 1.1]

#   #motor model
#   randomize_motor_model : False
#   motor_model_range:
#     hip : [22, 25]
#     thigh : [18, 22]
#     calf : [22, 25]
#   # friction
#   randomize_friction : True
#   friction_range : [-0.5, 1.25]

#   # base mass
#   randomize_base_mass : False

#   # rfi
#   randomize_torque_rfi : True
#   rfi_lim : 0.1
#   randomize_rfi_lim : False
#   rfi_lim_range : [0.9, 1.1]


#   # control delay
#   randomize_ctrl_delay : False
#   ctrl_delay_step_range : [0, 2] # integer max real delay is 90ms


### sysid_def_dr ####

# domain_rand:
#   # push robots
#   push_robots : False
#   push_interval_s : [15, 16]
#   max_push_vel_xy : 0.3

#   # base com
#   randomize_base_com : True
#   base_com_range:
#     x : [-0.1, 0.1]
#     y : [-0.1, 0.1]
#     z : [-0.1, 0.1]

#   # link mass
#   randomize_link_mass : True
#   link_mass_range : [0.8, 1.2]

#   # base inertia
#   randomize_base_inertia : True
#   base_inertia_range:
#     x : [-0.1, 0.1]
#     y : [-0.1, 0.1]
#     z : [-0.1, 0.1]

#   # pd gain
#   randomize_pd_gain : True
#   kp_range : [0.9, 1.1]
#   kd_range : [0.9, 1.1]

#   #motor model
#   randomize_motor_model : False
#   motor_model_range:
#     hip : [22, 24]
#     thigh : [18, 22]
#     calf : [22, 24]
#   # friction
#   randomize_friction : True
#   friction_range : [-0.5, 1.25]

#   # base mass
#   randomize_base_mass : False

#   # rfi
#   randomize_torque_rfi : True
#   rfi_lim : 0.1
#   randomize_rfi_lim : False
#   rfi_lim_range : [0.9, 1.1]


#   # control delay
#   randomize_ctrl_delay : False
#   ctrl_delay_step_range : [0, 2] # integer max real delay is 90ms


### sysid_uq_dr ####
domain_rand:
  # push robots
  push_robots : False
  push_interval_s : [15, 16]
  max_push_vel_xy : 0.3

  # base com
  randomize_base_com : True
  base_com_range:
    x : [0, 0.0165392]
    y : [0, 0.01482825]
    z : [0, 0.01539856]

  # link mass
  randomize_link_mass : True
  link_mass_range : [0.0, 1.2124]

  # base inertia
  randomize_base_inertia : True
  base_inertia_range:
    x : [0.0, 0.08953979]
    y : [0.0, 0.09695391]
    z : [0.0, 0.08554757]

  # pd gain
  randomize_pd_gain : True
  kp_range : [0.9, 1.1]
  kd_range : [0.9, 1.1]

  #motor model
  randomize_motor_model : True
  motor_model_range:
    hip : [22.727,0.513]
    thigh : [20.244, 0.582]
    calf : [22.702, 0.505]
  # friction
  randomize_friction : True
  friction_range : [-0.5, 1.25]

  # base mass
  randomize_base_mass : False

  # rfi
  randomize_torque_rfi : True
  rfi_lim : 0.1
  randomize_rfi_lim : False
  rfi_lim_range : [0.9, 1.1]


  # control delay
  randomize_ctrl_delay : False
  ctrl_delay_step_range : [0, 2] # integer max real delay is 90ms
