# @package _global_

defaults:
  - legged_base

# Env structure
env:
  _target_: spigym.envs.locomotion.go2_rp_track.go2_rp_track
  config:
    max_episode_length_s: 20
    locomotion_obs_scales:
      lin_vel: 1.0
      ang_vel: 1.0
      dof_pos: 1.0
      dof_vel: 1.0
      humanoid_commands_scale: 1.0
    locomotion_command_ranges:
      roll: [-0.5, 0.5]
      pitch: [-0.85, 0.85]
    locomotion_command_resampling_time: 5.0

    termination:
      terminate_by_contact: True # problematic in isaacgym when g1+terrain
      # terminate_by_lin_vel: False
      # terminate_by_ang_vel: False
      terminate_by_gravity: False
      terminate_by_low_height: True

    termination_scales:
      termination_min_base_height : 0.3
      # termination_max_base_vel : 10.0
      # termination_max_base_ang_vel : 5.0
      termination_gravity_x : 0.8
      termination_gravity_y : 0.8
      


# Globally accessible parameters
log_task_name: locomotion

eval_overrides:
  env:
    config: 
      max_episode_length_s: 100000
